package VO;

import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;

public class Data {
	public static ArrayList<Project> projectData = new ArrayList<>();

	//	public Data() {
	//	public static void addData(){
	static {
		//반 추가
		projectData.add(new Project("[Microsoft] 인공지능 sw 아카데미", "501호"));//
		projectData.add(new Project("데이터분석&AI엔지니어링 마스터 과정", "503호"));//5
		projectData.add(new Project("Node.js 백엔드 엔지니어 트랙", "507호"));//5
		projectData.add(new Project("Java&Spring 기반 풀스택 개발자 양성 과정", "804호"));//5
		projectData.add(new Project("생성형 ai 활용 msa기반 풀스택 교육", "901호"));//5
		projectData.add(new Project("Java 풀스택 아카데미", "902호"));//5
		//팀 추가
		projectData.get(0).addTeam(new Team("NeonCoders", 1));
		projectData.get(0).addTeam(new Team("BitByBit", 1));
		projectData.get(0).addTeam(new Team("코드앤소울", 1));
		projectData.get(0).addTeam(new Team("DevVerse", 1));
		projectData.get(0).addTeam(new Team("Studio404", 2));
		projectData.get(0).addTeam(new Team("Codyssey", 2));
		projectData.get(0).addTeam(new Team("PixelPushers", 2));
		projectData.get(0).addTeam(new Team("VibeCoders", 2));
		projectData.get(0).addTeam(new Team("Canvas.dev", 3));
		projectData.get(0).addTeam(new Team("CodeBloom", 3));
		projectData.get(0).addTeam(new Team("레벨업코더", 3));
		projectData.get(0).addTeam(new Team("파이널디버그", 3));
		projectData.get(0).addTeam(new Team("코딩몬스터", 4));
		projectData.get(0).addTeam(new Team("스타개발단", 4));
		projectData.get(0).addTeam(new Team("젤다의개발자", 4));
		projectData.get(0).addTeam(new Team("코드워즈", 4));
		projectData.get(1).addTeam(new Team("어몽코더스", 1));
		projectData.get(1).addTeam(new Team("갓겜개발자들", 1));
		projectData.get(1).addTeam(new Team("롤백엔더스", 1));
		projectData.get(1).addTeam(new Team("너의코드를믿어", 1));
		projectData.get(1).addTeam(new Team("이노코드", 2));
		projectData.get(1).addTeam(new Team("코드맛집", 2));
		projectData.get(1).addTeam(new Team("멘붕개발단", 2));
		projectData.get(1).addTeam(new Team("야근장인들", 2));
		projectData.get(1).addTeam(new Team("코딩의민족", 3));
		projectData.get(1).addTeam(new Team("함수가족", 3));
		projectData.get(1).addTeam(new Team("마감요정들", 3));
		projectData.get(1).addTeam(new Team("코드장인들", 3));
		projectData.get(1).addTeam(new Team("안자고코딩해", 4));
		projectData.get(1).addTeam(new Team("오류는내운명", 4));
		projectData.get(1).addTeam(new Team("코드토끼", 4));
		projectData.get(1).addTeam(new Team("디지털사무라이", 4));
		projectData.get(2).addTeam(new Team("버그버스터즈", 1));
		projectData.get(2).addTeam(new Team("키보드캣츠", 1));
		projectData.get(2).addTeam(new Team("알고리듬베이커리", 1));
		projectData.get(2).addTeam(new Team("해커톤히어로즈", 1));
		projectData.get(2).addTeam(new Team("무한루프러버즈", 2));
		projectData.get(2).addTeam(new Team("세그폴트세대", 2));
		projectData.get(2).addTeam(new Team("HTML하마들", 2));
		projectData.get(2).addTeam(new Team("개발자도감", 2));
		projectData.get(2).addTeam(new Team("포트폴리오빌더즈", 3));
		projectData.get(2).addTeam(new Team("데브챌린저스", 3));
		projectData.get(2).addTeam(new Team("오늘도성장", 3));
		projectData.get(2).addTeam(new Team("코딩하루한줄", 3));
		projectData.get(2).addTeam(new Team("DevUp", 4));
		projectData.get(2).addTeam(new Team("코드온더라이즈", 4));
		projectData.get(2).addTeam(new Team("쌓고또쌓고", 4));
		projectData.get(2).addTeam(new Team("도전하는개발자들", 4));
		projectData.get(3).addTeam(new Team("NEXT.js Generation", 1));
		projectData.get(3).addTeam(new Team("나노코더스", 1));
		projectData.get(3).addTeam(new Team("DevStorm", 1));
		projectData.get(3).addTeam(new Team("코드파이터즈", 1));
		projectData.get(3).addTeam(new Team("Project Phoenix", 2));
		projectData.get(3).addTeam(new Team("블랙핵커즈", 2));
		projectData.get(3).addTeam(new Team("Reboot Rebels", 2));
		projectData.get(3).addTeam(new Team("Infinity Coders", 2));
		projectData.get(3).addTeam(new Team("CodeCore", 3));
		projectData.get(3).addTeam(new Team("HackForge", 3));
		projectData.get(3).addTeam(new Team("IronStack", 3));
		projectData.get(3).addTeam(new Team("Command+Team", 3));
		projectData.get(3).addTeam(new Team("ThinkCode", 4));
		projectData.get(3).addTeam(new Team("Codetelligence", 4));
		projectData.get(3).addTeam(new Team("알고리듬스쿼드", 4));
		projectData.get(3).addTeam(new Team("창조적파괴자들", 4));
		projectData.get(4).addTeam(new Team("Big O Boys", 1));
		projectData.get(4).addTeam(new Team("SmartStack", 1));
		projectData.get(4).addTeam(new Team("MindBuilders", 1));
		projectData.get(4).addTeam(new Team("DevDynamos", 1));
		projectData.get(4).addTeam(new Team("IDEA팀", 2));
		projectData.get(4).addTeam(new Team("혁신코더스", 2));
		projectData.get(4).addTeam(new Team("코드좀짬", 2));
		projectData.get(4).addTeam(new Team("얼렁뚱땅팀", 2));
		projectData.get(4).addTeam(new Team("안되면되게하라", 3));
		projectData.get(4).addTeam(new Team("어디서든코딩", 3));
		projectData.get(4).addTeam(new Team("불타는코더들", 3));
		projectData.get(4).addTeam(new Team("야근은싫어요", 3));
		projectData.get(4).addTeam(new Team("이게되네팀", 4));
		projectData.get(4).addTeam(new Team("페이지404", 4));
		projectData.get(4).addTeam(new Team("일단만들고보자", 4));
		projectData.get(4).addTeam(new Team("잘될지도몰라", 4));
		projectData.get(5).addTeam(new Team("코딩고민상담소", 1));
		projectData.get(5).addTeam(new Team("시간없조", 1));
		projectData.get(5).addTeam(new Team("구글링장인들", 1));
		projectData.get(5).addTeam(new Team("개발?우리가하조", 1));
		projectData.get(5).addTeam(new Team("버그는우리친구", 2));
		projectData.get(5).addTeam(new Team("키보드워리어즈", 2));
		projectData.get(5).addTeam(new Team("디버그생활", 2));
		projectData.get(5).addTeam(new Team("수면보다개발", 2));
		projectData.get(5).addTeam(new Team("커피앤코드", 3));
		projectData.get(5).addTeam(new Team("TMI Devs", 3));
		projectData.get(5).addTeam(new Team("코드국민", 3));
		projectData.get(5).addTeam(new Team("디버깅은내운명", 3));
		projectData.get(5).addTeam(new Team("괜찮아커밋했어", 4));
		projectData.get(5).addTeam(new Team("풀스택맛집", 4));
		projectData.get(5).addTeam(new Team("일단돌려보자", 4));
		projectData.get(5).addTeam(new Team("함수형사건", 4));
		//학생 추가
		ArrayList<Student> class1Student = new ArrayList<Student>();
		ArrayList<Student> class2Student = new ArrayList<Student>();
		ArrayList<Student> class3Student = new ArrayList<Student>();
		ArrayList<Student> class4Student = new ArrayList<Student>();
		ArrayList<Student> class5Student = new ArrayList<Student>();
		ArrayList<Student> class6Student = new ArrayList<Student>();
		class1Student.add(new Student("김민준", "010-7886-6877"));
		class1Student.add(new Student("임채원", "010-0593-1736"));
		class1Student.add(new Student("신도윤", "010-5379-1990"));
		class1Student.add(new Student("최윤성", "010-8514-6115"));
		class1Student.add(new Student("오지민", "010-4279-3455"));
		class1Student.add(new Student("노태윤", "010-6882-7422"));
		class1Student.add(new Student("강예준", "010-0085-6575"));
		class1Student.add(new Student("문태현", "010-3631-5353"));
		class1Student.add(new Student("이도윤", "010-7424-8442"));
		class1Student.add(new Student("송유나", "010-4994-5239"));
		class1Student.add(new Student("남다은", "010-9937-3187"));
		class1Student.add(new Student("정도윤", "010-5657-0873"));
		class1Student.add(new Student("서하진", "010-4313-9748"));
		class1Student.add(new Student("유예진", "010-8570-0656"));
		class1Student.add(new Student("윤아린", "010-7488-8073"));
		class1Student.add(new Student("백윤재", "010-8891-6215"));
		class2Student.add(new Student("박하영", "010-7294-2696"));
		class2Student.add(new Student("한하람", "010-3773-5417"));
		class2Student.add(new Student("장가은", "010-2812-3310"));
		class2Student.add(new Student("조하늘", "010-8479-4819"));
		class2Student.add(new Student("홍채원", "010-9692-8426"));
		class2Student.add(new Student("김하영", "010-9090-8676"));
		class2Student.add(new Student("조민재", "010-7548-3976"));
		class2Student.add(new Student("홍지후", "010-1515-3293"));
		class2Student.add(new Student("김가은", "010-4456-1073"));
		class2Student.add(new Student("임하은", "010-9009-0632"));
		class2Student.add(new Student("신예지", "010-3170-6219"));
		class2Student.add(new Student("최하람", "010-6699-7571"));
		class2Student.add(new Student("오지아", "010-4700-6552"));
		class2Student.add(new Student("노다연", "010-3264-9106"));
		class2Student.add(new Student("강하늘", "010-0440-3682"));
		class2Student.add(new Student("문지호", "010-0592-6598"));
		class3Student.add(new Student("이서아", "010-6795-0909"));
		class3Student.add(new Student("송예빈", "010-5321-1040"));
		class3Student.add(new Student("남하율", "010-0381-0953"));
		class3Student.add(new Student("정하은", "010-2905-8291"));
		class3Student.add(new Student("서채원", "010-9021-2131"));
		class3Student.add(new Student("유채영", "010-2210-8611"));
		class3Student.add(new Student("윤예린", "010-3047-5117"));
		class3Student.add(new Student("백윤서", "010-7401-7265"));
		class3Student.add(new Student("박지안", "010-3832-2827"));
		class3Student.add(new Student("한예준", "010-2522-7972"));
		class3Student.add(new Student("장하은", "010-6047-7617"));
		class3Student.add(new Student("최예린", "010-0295-1919"));
		class3Student.add(new Student("오세현", "010-7994-5960"));
		class3Student.add(new Student("노하영", "010-2092-2288"));
		class3Student.add(new Student("강서아", "010-0087-0576"));
		class3Student.add(new Student("문하율", "010-4904-1352"));
		class4Student.add(new Student("이준호", "010-7022-8203"));
		class4Student.add(new Student("송윤아", "010-8400-2435"));
		class4Student.add(new Student("남지후", "010-2379-3276"));
		class4Student.add(new Student("정예서", "010-4699-2636"));
		class4Student.add(new Student("서승우", "010-2031-5899"));
		class4Student.add(new Student("유세린", "010-2330-5898"));
		class4Student.add(new Student("윤하린", "010-2667-9528"));
		class4Student.add(new Student("백지후", "010-4023-1353"));
		class4Student.add(new Student("박우진", "010-0326-6638"));
		class4Student.add(new Student("한예찬", "010-9238-2239"));
		class4Student.add(new Student("장도윤", "010-6702-4960"));
		class4Student.add(new Student("조지안", "010-3006-9882"));
		class4Student.add(new Student("홍서아", "010-2307-9629"));
		class4Student.add(new Student("김태윤", "010-1787-1155"));
		class4Student.add(new Student("임서아", "010-7598-0144"));
		class4Student.add(new Student("신다은", "010-7641-4864"));
		class5Student.add(new Student("강다은", "010-1022-3782"));
		class5Student.add(new Student("문수민", "010-6513-3694"));
		class5Student.add(new Student("이지후", "010-0770-7833"));
		class5Student.add(new Student("송지훈", "010-5947-8973"));
		class5Student.add(new Student("남건우", "010-5411-0394"));
		class5Student.add(new Student("정지호", "010-8892-2871"));
		class5Student.add(new Student("서지후", "010-3918-3085"));
		class5Student.add(new Student("유하진", "010-8880-3931"));
		class5Student.add(new Student("윤서영", "010-1861-5937"));
		class5Student.add(new Student("백하린", "010-1084-8269"));
		class5Student.add(new Student("박태윤", "010-4239-8139"));
		class5Student.add(new Student("한채은", "010-6558-9136"));
		class5Student.add(new Student("장유진", "010-3996-4850"));
		class5Student.add(new Student("조다인", "010-2821-4618"));
		class5Student.add(new Student("홍예나", "010-3374-1679"));
		class5Student.add(new Student("김지우", "010-3129-7212"));
		class6Student.add(new Student("임지호", "010-6398-7125"));
		class6Student.add(new Student("신예서", "010-6055-1646"));
		class6Student.add(new Student("최은채", "010-0457-4109"));
		class6Student.add(new Student("오유진", "010-5407-7180"));
		class6Student.add(new Student("노예진", "010-6684-2387"));
		class6Student.add(new Student("윤지호", "010-6611-2825"));
		class6Student.add(new Student("백하진", "010-4644-7196"));
		class6Student.add(new Student("박채린", "010-4312-9141"));
		class6Student.add(new Student("한수아", "010-6477-7545"));
		class6Student.add(new Student("장예린", "010-9149-6022"));
		class6Student.add(new Student("조하은", "010-4043-9696"));
		class6Student.add(new Student("홍서연", "010-6571-9602"));
		class6Student.add(new Student("김채은", "010-2774-3906"));
		class6Student.add(new Student("임예찬", "010-8061-8977"));
		class6Student.add(new Student("신정우", "010-4547-3074"));
		class6Student.add(new Student("최민지", "010-1695-1755"));
		//팀원 추가
		projectData.get(0).getTeams2().get(0).addMember(class1Student.get(11));
		projectData.get(0).getTeams2().get(0).addMember(class1Student.get(10));
		projectData.get(0).getTeams2().get(0).addMember(class1Student.get(4));
		projectData.get(0).getTeams2().get(0).addMember(class1Student.get(5));
		projectData.get(0).getTeams2().get(1).addMember(class1Student.get(0));
		projectData.get(0).getTeams2().get(1).addMember(class1Student.get(12));
		projectData.get(0).getTeams2().get(1).addMember(class1Student.get(14));
		projectData.get(0).getTeams2().get(1).addMember(class1Student.get(8));
		projectData.get(0).getTeams2().get(2).addMember(class1Student.get(3));
		projectData.get(0).getTeams2().get(2).addMember(class1Student.get(1));
		projectData.get(0).getTeams2().get(2).addMember(class1Student.get(6));
		projectData.get(0).getTeams2().get(2).addMember(class1Student.get(13));
		projectData.get(0).getTeams2().get(3).addMember(class1Student.get(9));
		projectData.get(0).getTeams2().get(3).addMember(class1Student.get(15));
		projectData.get(0).getTeams2().get(3).addMember(class1Student.get(2));
		projectData.get(0).getTeams2().get(3).addMember(class1Student.get(7));
		projectData.get(0).getTeams2().get(4).addMember(class1Student.get(2));
		projectData.get(0).getTeams2().get(4).addMember(class1Student.get(5));
		projectData.get(0).getTeams2().get(4).addMember(class1Student.get(6));
		projectData.get(0).getTeams2().get(4).addMember(class1Student.get(15));
		projectData.get(0).getTeams2().get(5).addMember(class1Student.get(14));
		projectData.get(0).getTeams2().get(5).addMember(class1Student.get(12));
		projectData.get(0).getTeams2().get(5).addMember(class1Student.get(9));
		projectData.get(0).getTeams2().get(5).addMember(class1Student.get(1));
		projectData.get(0).getTeams2().get(6).addMember(class1Student.get(7));
		projectData.get(0).getTeams2().get(6).addMember(class1Student.get(11));
		projectData.get(0).getTeams2().get(6).addMember(class1Student.get(3));
		projectData.get(0).getTeams2().get(6).addMember(class1Student.get(10));
		projectData.get(0).getTeams2().get(7).addMember(class1Student.get(13));
		projectData.get(0).getTeams2().get(7).addMember(class1Student.get(8));
		projectData.get(0).getTeams2().get(7).addMember(class1Student.get(0));
		projectData.get(0).getTeams2().get(7).addMember(class1Student.get(4));
		projectData.get(0).getTeams2().get(8).addMember(class1Student.get(6));
		projectData.get(0).getTeams2().get(8).addMember(class1Student.get(0));
		projectData.get(0).getTeams2().get(8).addMember(class1Student.get(3));
		projectData.get(0).getTeams2().get(8).addMember(class1Student.get(7));
		projectData.get(0).getTeams2().get(9).addMember(class1Student.get(2));
		projectData.get(0).getTeams2().get(9).addMember(class1Student.get(15));
		projectData.get(0).getTeams2().get(9).addMember(class1Student.get(8));
		projectData.get(0).getTeams2().get(9).addMember(class1Student.get(12));
		projectData.get(0).getTeams2().get(10).addMember(class1Student.get(4));
		projectData.get(0).getTeams2().get(10).addMember(class1Student.get(1));
		projectData.get(0).getTeams2().get(10).addMember(class1Student.get(11));
		projectData.get(0).getTeams2().get(10).addMember(class1Student.get(9));
		projectData.get(0).getTeams2().get(11).addMember(class1Student.get(13));
		projectData.get(0).getTeams2().get(11).addMember(class1Student.get(14));
		projectData.get(0).getTeams2().get(11).addMember(class1Student.get(5));
		projectData.get(0).getTeams2().get(11).addMember(class1Student.get(10));
		projectData.get(0).getTeams2().get(12).addMember(class1Student.get(2));
		projectData.get(0).getTeams2().get(12).addMember(class1Student.get(15));
		projectData.get(0).getTeams2().get(12).addMember(class1Student.get(5));
		projectData.get(0).getTeams2().get(12).addMember(class1Student.get(12));
		projectData.get(0).getTeams2().get(13).addMember(class1Student.get(4));
		projectData.get(0).getTeams2().get(13).addMember(class1Student.get(0));
		projectData.get(0).getTeams2().get(13).addMember(class1Student.get(6));
		projectData.get(0).getTeams2().get(13).addMember(class1Student.get(10));
		projectData.get(0).getTeams2().get(14).addMember(class1Student.get(14));
		projectData.get(0).getTeams2().get(14).addMember(class1Student.get(7));
		projectData.get(0).getTeams2().get(14).addMember(class1Student.get(3));
		projectData.get(0).getTeams2().get(14).addMember(class1Student.get(1));
		projectData.get(0).getTeams2().get(15).addMember(class1Student.get(8));
		projectData.get(0).getTeams2().get(15).addMember(class1Student.get(11));
		projectData.get(0).getTeams2().get(15).addMember(class1Student.get(13));
		projectData.get(0).getTeams2().get(15).addMember(class1Student.get(9));
		projectData.get(1).getTeams2().get(0).addMember(class2Student.get(13));
		projectData.get(1).getTeams2().get(0).addMember(class2Student.get(14));
		projectData.get(1).getTeams2().get(0).addMember(class2Student.get(11));
		projectData.get(1).getTeams2().get(0).addMember(class2Student.get(4));
		projectData.get(1).getTeams2().get(1).addMember(class2Student.get(2));
		projectData.get(1).getTeams2().get(1).addMember(class2Student.get(12));
		projectData.get(1).getTeams2().get(1).addMember(class2Student.get(9));
		projectData.get(1).getTeams2().get(1).addMember(class2Student.get(3));
		projectData.get(1).getTeams2().get(2).addMember(class2Student.get(7));
		projectData.get(1).getTeams2().get(2).addMember(class2Student.get(1));
		projectData.get(1).getTeams2().get(2).addMember(class2Student.get(0));
		projectData.get(1).getTeams2().get(2).addMember(class2Student.get(5));
		projectData.get(1).getTeams2().get(3).addMember(class2Student.get(8));
		projectData.get(1).getTeams2().get(3).addMember(class2Student.get(10));
		projectData.get(1).getTeams2().get(3).addMember(class2Student.get(15));
		projectData.get(1).getTeams2().get(3).addMember(class2Student.get(6));
		projectData.get(1).getTeams2().get(4).addMember(class2Student.get(3));
		projectData.get(1).getTeams2().get(4).addMember(class2Student.get(13));
		projectData.get(1).getTeams2().get(4).addMember(class2Student.get(4));
		projectData.get(1).getTeams2().get(4).addMember(class2Student.get(6));
		projectData.get(1).getTeams2().get(5).addMember(class2Student.get(5));
		projectData.get(1).getTeams2().get(5).addMember(class2Student.get(2));
		projectData.get(1).getTeams2().get(5).addMember(class2Student.get(9));
		projectData.get(1).getTeams2().get(5).addMember(class2Student.get(8));
		projectData.get(1).getTeams2().get(6).addMember(class2Student.get(7));
		projectData.get(1).getTeams2().get(6).addMember(class2Student.get(1));
		projectData.get(1).getTeams2().get(6).addMember(class2Student.get(12));
		projectData.get(1).getTeams2().get(6).addMember(class2Student.get(11));
		projectData.get(1).getTeams2().get(7).addMember(class2Student.get(0));
		projectData.get(1).getTeams2().get(7).addMember(class2Student.get(14));
		projectData.get(1).getTeams2().get(7).addMember(class2Student.get(10));
		projectData.get(1).getTeams2().get(7).addMember(class2Student.get(15));
		projectData.get(1).getTeams2().get(8).addMember(class2Student.get(9));
		projectData.get(1).getTeams2().get(8).addMember(class2Student.get(0));
		projectData.get(1).getTeams2().get(8).addMember(class2Student.get(7));
		projectData.get(1).getTeams2().get(8).addMember(class2Student.get(14));
		projectData.get(1).getTeams2().get(9).addMember(class2Student.get(3));
		projectData.get(1).getTeams2().get(9).addMember(class2Student.get(1));
		projectData.get(1).getTeams2().get(9).addMember(class2Student.get(5));
		projectData.get(1).getTeams2().get(9).addMember(class2Student.get(13));
		projectData.get(1).getTeams2().get(10).addMember(class2Student.get(11));
		projectData.get(1).getTeams2().get(10).addMember(class2Student.get(2));
		projectData.get(1).getTeams2().get(10).addMember(class2Student.get(4));
		projectData.get(1).getTeams2().get(10).addMember(class2Student.get(8));
		projectData.get(1).getTeams2().get(11).addMember(class2Student.get(12));
		projectData.get(1).getTeams2().get(11).addMember(class2Student.get(15));
		projectData.get(1).getTeams2().get(11).addMember(class2Student.get(10));
		projectData.get(1).getTeams2().get(11).addMember(class2Student.get(6));
		projectData.get(1).getTeams2().get(12).addMember(class2Student.get(13));
		projectData.get(1).getTeams2().get(12).addMember(class2Student.get(5));
		projectData.get(1).getTeams2().get(12).addMember(class2Student.get(9));
		projectData.get(1).getTeams2().get(12).addMember(class2Student.get(6));
		projectData.get(1).getTeams2().get(13).addMember(class2Student.get(0));
		projectData.get(1).getTeams2().get(13).addMember(class2Student.get(10));
		projectData.get(1).getTeams2().get(13).addMember(class2Student.get(8));
		projectData.get(1).getTeams2().get(13).addMember(class2Student.get(2));
		projectData.get(1).getTeams2().get(14).addMember(class2Student.get(4));
		projectData.get(1).getTeams2().get(14).addMember(class2Student.get(15));
		projectData.get(1).getTeams2().get(14).addMember(class2Student.get(1));
		projectData.get(1).getTeams2().get(14).addMember(class2Student.get(12));
		projectData.get(1).getTeams2().get(15).addMember(class2Student.get(7));
		projectData.get(1).getTeams2().get(15).addMember(class2Student.get(11));
		projectData.get(1).getTeams2().get(15).addMember(class2Student.get(14));
		projectData.get(1).getTeams2().get(15).addMember(class2Student.get(3));
		projectData.get(2).getTeams2().get(0).addMember(class3Student.get(3));
		projectData.get(2).getTeams2().get(0).addMember(class3Student.get(2));
		projectData.get(2).getTeams2().get(0).addMember(class3Student.get(1));
		projectData.get(2).getTeams2().get(0).addMember(class3Student.get(6));
		projectData.get(2).getTeams2().get(1).addMember(class3Student.get(5));
		projectData.get(2).getTeams2().get(1).addMember(class3Student.get(14));
		projectData.get(2).getTeams2().get(1).addMember(class3Student.get(7));
		projectData.get(2).getTeams2().get(1).addMember(class3Student.get(8));
		projectData.get(2).getTeams2().get(2).addMember(class3Student.get(13));
		projectData.get(2).getTeams2().get(2).addMember(class3Student.get(12));
		projectData.get(2).getTeams2().get(2).addMember(class3Student.get(4));
		projectData.get(2).getTeams2().get(2).addMember(class3Student.get(9));
		projectData.get(2).getTeams2().get(3).addMember(class3Student.get(10));
		projectData.get(2).getTeams2().get(3).addMember(class3Student.get(15));
		projectData.get(2).getTeams2().get(3).addMember(class3Student.get(11));
		projectData.get(2).getTeams2().get(3).addMember(class3Student.get(0));
		projectData.get(2).getTeams2().get(4).addMember(class3Student.get(8));
		projectData.get(2).getTeams2().get(4).addMember(class3Student.get(13));
		projectData.get(2).getTeams2().get(4).addMember(class3Student.get(9));
		projectData.get(2).getTeams2().get(4).addMember(class3Student.get(2));
		projectData.get(2).getTeams2().get(5).addMember(class3Student.get(0));
		projectData.get(2).getTeams2().get(5).addMember(class3Student.get(6));
		projectData.get(2).getTeams2().get(5).addMember(class3Student.get(4));
		projectData.get(2).getTeams2().get(5).addMember(class3Student.get(10));
		projectData.get(2).getTeams2().get(6).addMember(class3Student.get(11));
		projectData.get(2).getTeams2().get(6).addMember(class3Student.get(5));
		projectData.get(2).getTeams2().get(6).addMember(class3Student.get(3));
		projectData.get(2).getTeams2().get(6).addMember(class3Student.get(15));
		projectData.get(2).getTeams2().get(7).addMember(class3Student.get(1));
		projectData.get(2).getTeams2().get(7).addMember(class3Student.get(14));
		projectData.get(2).getTeams2().get(7).addMember(class3Student.get(12));
		projectData.get(2).getTeams2().get(7).addMember(class3Student.get(7));
		projectData.get(2).getTeams2().get(8).addMember(class3Student.get(1));
		projectData.get(2).getTeams2().get(8).addMember(class3Student.get(12));
		projectData.get(2).getTeams2().get(8).addMember(class3Student.get(0));
		projectData.get(2).getTeams2().get(8).addMember(class3Student.get(11));
		projectData.get(2).getTeams2().get(9).addMember(class3Student.get(10));
		projectData.get(2).getTeams2().get(9).addMember(class3Student.get(4));
		projectData.get(2).getTeams2().get(9).addMember(class3Student.get(9));
		projectData.get(2).getTeams2().get(9).addMember(class3Student.get(7));
		projectData.get(2).getTeams2().get(10).addMember(class3Student.get(8));
		projectData.get(2).getTeams2().get(10).addMember(class3Student.get(13));
		projectData.get(2).getTeams2().get(10).addMember(class3Student.get(6));
		projectData.get(2).getTeams2().get(10).addMember(class3Student.get(14));
		projectData.get(2).getTeams2().get(11).addMember(class3Student.get(15));
		projectData.get(2).getTeams2().get(11).addMember(class3Student.get(3));
		projectData.get(2).getTeams2().get(11).addMember(class3Student.get(2));
		projectData.get(2).getTeams2().get(11).addMember(class3Student.get(5));
		projectData.get(2).getTeams2().get(12).addMember(class3Student.get(5));
		projectData.get(2).getTeams2().get(12).addMember(class3Student.get(13));
		projectData.get(2).getTeams2().get(12).addMember(class3Student.get(11));
		projectData.get(2).getTeams2().get(12).addMember(class3Student.get(10));
		projectData.get(2).getTeams2().get(13).addMember(class3Student.get(6));
		projectData.get(2).getTeams2().get(13).addMember(class3Student.get(7));
		projectData.get(2).getTeams2().get(13).addMember(class3Student.get(12));
		projectData.get(2).getTeams2().get(13).addMember(class3Student.get(15));
		projectData.get(2).getTeams2().get(14).addMember(class3Student.get(0));
		projectData.get(2).getTeams2().get(14).addMember(class3Student.get(14));
		projectData.get(2).getTeams2().get(14).addMember(class3Student.get(9));
		projectData.get(2).getTeams2().get(14).addMember(class3Student.get(2));
		projectData.get(2).getTeams2().get(15).addMember(class3Student.get(1));
		projectData.get(2).getTeams2().get(15).addMember(class3Student.get(3));
		projectData.get(2).getTeams2().get(15).addMember(class3Student.get(8));
		projectData.get(2).getTeams2().get(15).addMember(class3Student.get(4));
		projectData.get(3).getTeams2().get(0).addMember(class4Student.get(15));
		projectData.get(3).getTeams2().get(0).addMember(class4Student.get(0));
		projectData.get(3).getTeams2().get(0).addMember(class4Student.get(12));
		projectData.get(3).getTeams2().get(0).addMember(class4Student.get(2));
		projectData.get(3).getTeams2().get(1).addMember(class4Student.get(11));
		projectData.get(3).getTeams2().get(1).addMember(class4Student.get(6));
		projectData.get(3).getTeams2().get(1).addMember(class4Student.get(1));
		projectData.get(3).getTeams2().get(1).addMember(class4Student.get(9));
		projectData.get(3).getTeams2().get(2).addMember(class4Student.get(14));
		projectData.get(3).getTeams2().get(2).addMember(class4Student.get(8));
		projectData.get(3).getTeams2().get(2).addMember(class4Student.get(10));
		projectData.get(3).getTeams2().get(2).addMember(class4Student.get(5));
		projectData.get(3).getTeams2().get(3).addMember(class4Student.get(4));
		projectData.get(3).getTeams2().get(3).addMember(class4Student.get(3));
		projectData.get(3).getTeams2().get(3).addMember(class4Student.get(13));
		projectData.get(3).getTeams2().get(3).addMember(class4Student.get(7));
		projectData.get(3).getTeams2().get(4).addMember(class4Student.get(15));
		projectData.get(3).getTeams2().get(4).addMember(class4Student.get(9));
		projectData.get(3).getTeams2().get(4).addMember(class4Student.get(0));
		projectData.get(3).getTeams2().get(4).addMember(class4Student.get(2));
		projectData.get(3).getTeams2().get(5).addMember(class4Student.get(10));
		projectData.get(3).getTeams2().get(5).addMember(class4Student.get(4));
		projectData.get(3).getTeams2().get(5).addMember(class4Student.get(12));
		projectData.get(3).getTeams2().get(5).addMember(class4Student.get(7));
		projectData.get(3).getTeams2().get(6).addMember(class4Student.get(14));
		projectData.get(3).getTeams2().get(6).addMember(class4Student.get(8));
		projectData.get(3).getTeams2().get(6).addMember(class4Student.get(11));
		projectData.get(3).getTeams2().get(6).addMember(class4Student.get(6));
		projectData.get(3).getTeams2().get(7).addMember(class4Student.get(5));
		projectData.get(3).getTeams2().get(7).addMember(class4Student.get(13));
		projectData.get(3).getTeams2().get(7).addMember(class4Student.get(1));
		projectData.get(3).getTeams2().get(7).addMember(class4Student.get(3));
		projectData.get(3).getTeams2().get(8).addMember(class4Student.get(0));
		projectData.get(3).getTeams2().get(8).addMember(class4Student.get(4));
		projectData.get(3).getTeams2().get(8).addMember(class4Student.get(9));
		projectData.get(3).getTeams2().get(8).addMember(class4Student.get(3));
		projectData.get(3).getTeams2().get(9).addMember(class4Student.get(6));
		projectData.get(3).getTeams2().get(9).addMember(class4Student.get(8));
		projectData.get(3).getTeams2().get(9).addMember(class4Student.get(1));
		projectData.get(3).getTeams2().get(9).addMember(class4Student.get(12));
		projectData.get(3).getTeams2().get(10).addMember(class4Student.get(7));
		projectData.get(3).getTeams2().get(10).addMember(class4Student.get(13));
		projectData.get(3).getTeams2().get(10).addMember(class4Student.get(15));
		projectData.get(3).getTeams2().get(10).addMember(class4Student.get(14));
		projectData.get(3).getTeams2().get(11).addMember(class4Student.get(10));
		projectData.get(3).getTeams2().get(11).addMember(class4Student.get(11));
		projectData.get(3).getTeams2().get(11).addMember(class4Student.get(2));
		projectData.get(3).getTeams2().get(11).addMember(class4Student.get(5));
		projectData.get(3).getTeams2().get(12).addMember(class4Student.get(4));
		projectData.get(3).getTeams2().get(12).addMember(class4Student.get(3));
		projectData.get(3).getTeams2().get(12).addMember(class4Student.get(5));
		projectData.get(3).getTeams2().get(12).addMember(class4Student.get(13));
		projectData.get(3).getTeams2().get(13).addMember(class4Student.get(2));
		projectData.get(3).getTeams2().get(13).addMember(class4Student.get(11));
		projectData.get(3).getTeams2().get(13).addMember(class4Student.get(12));
		projectData.get(3).getTeams2().get(13).addMember(class4Student.get(0));
		projectData.get(3).getTeams2().get(14).addMember(class4Student.get(15));
		projectData.get(3).getTeams2().get(14).addMember(class4Student.get(14));
		projectData.get(3).getTeams2().get(14).addMember(class4Student.get(6));
		projectData.get(3).getTeams2().get(14).addMember(class4Student.get(10));
		projectData.get(3).getTeams2().get(15).addMember(class4Student.get(8));
		projectData.get(3).getTeams2().get(15).addMember(class4Student.get(1));
		projectData.get(3).getTeams2().get(15).addMember(class4Student.get(9));
		projectData.get(3).getTeams2().get(15).addMember(class4Student.get(7));
		projectData.get(4).getTeams2().get(0).addMember(class5Student.get(5));
		projectData.get(4).getTeams2().get(0).addMember(class5Student.get(2));
		projectData.get(4).getTeams2().get(0).addMember(class5Student.get(10));
		projectData.get(4).getTeams2().get(0).addMember(class5Student.get(13));
		projectData.get(4).getTeams2().get(1).addMember(class5Student.get(0));
		projectData.get(4).getTeams2().get(1).addMember(class5Student.get(8));
		projectData.get(4).getTeams2().get(1).addMember(class5Student.get(1));
		projectData.get(4).getTeams2().get(1).addMember(class5Student.get(11));
		projectData.get(4).getTeams2().get(2).addMember(class5Student.get(7));
		projectData.get(4).getTeams2().get(2).addMember(class5Student.get(4));
		projectData.get(4).getTeams2().get(2).addMember(class5Student.get(12));
		projectData.get(4).getTeams2().get(2).addMember(class5Student.get(6));
		projectData.get(4).getTeams2().get(3).addMember(class5Student.get(3));
		projectData.get(4).getTeams2().get(3).addMember(class5Student.get(14));
		projectData.get(4).getTeams2().get(3).addMember(class5Student.get(15));
		projectData.get(4).getTeams2().get(3).addMember(class5Student.get(9));
		projectData.get(4).getTeams2().get(4).addMember(class5Student.get(11));
		projectData.get(4).getTeams2().get(4).addMember(class5Student.get(4));
		projectData.get(4).getTeams2().get(4).addMember(class5Student.get(9));
		projectData.get(4).getTeams2().get(4).addMember(class5Student.get(5));
		projectData.get(4).getTeams2().get(5).addMember(class5Student.get(12));
		projectData.get(4).getTeams2().get(5).addMember(class5Student.get(10));
		projectData.get(4).getTeams2().get(5).addMember(class5Student.get(8));
		projectData.get(4).getTeams2().get(5).addMember(class5Student.get(1));
		projectData.get(4).getTeams2().get(6).addMember(class5Student.get(15));
		projectData.get(4).getTeams2().get(6).addMember(class5Student.get(3));
		projectData.get(4).getTeams2().get(6).addMember(class5Student.get(14));
		projectData.get(4).getTeams2().get(6).addMember(class5Student.get(6));
		projectData.get(4).getTeams2().get(7).addMember(class5Student.get(7));
		projectData.get(4).getTeams2().get(7).addMember(class5Student.get(13));
		projectData.get(4).getTeams2().get(7).addMember(class5Student.get(0));
		projectData.get(4).getTeams2().get(7).addMember(class5Student.get(2));
		projectData.get(4).getTeams2().get(8).addMember(class5Student.get(6));
		projectData.get(4).getTeams2().get(8).addMember(class5Student.get(0));
		projectData.get(4).getTeams2().get(8).addMember(class5Student.get(12));
		projectData.get(4).getTeams2().get(8).addMember(class5Student.get(13));
		projectData.get(4).getTeams2().get(9).addMember(class5Student.get(10));
		projectData.get(4).getTeams2().get(9).addMember(class5Student.get(4));
		projectData.get(4).getTeams2().get(9).addMember(class5Student.get(14));
		projectData.get(4).getTeams2().get(9).addMember(class5Student.get(8));
		projectData.get(4).getTeams2().get(10).addMember(class5Student.get(1));
		projectData.get(4).getTeams2().get(10).addMember(class5Student.get(7));
		projectData.get(4).getTeams2().get(10).addMember(class5Student.get(5));
		projectData.get(4).getTeams2().get(10).addMember(class5Student.get(2));
		projectData.get(4).getTeams2().get(11).addMember(class5Student.get(9));
		projectData.get(4).getTeams2().get(11).addMember(class5Student.get(15));
		projectData.get(4).getTeams2().get(11).addMember(class5Student.get(11));
		projectData.get(4).getTeams2().get(11).addMember(class5Student.get(3));
		projectData.get(4).getTeams2().get(12).addMember(class5Student.get(3));
		projectData.get(4).getTeams2().get(12).addMember(class5Student.get(2));
		projectData.get(4).getTeams2().get(12).addMember(class5Student.get(5));
		projectData.get(4).getTeams2().get(12).addMember(class5Student.get(9));
		projectData.get(4).getTeams2().get(13).addMember(class5Student.get(12));
		projectData.get(4).getTeams2().get(13).addMember(class5Student.get(10));
		projectData.get(4).getTeams2().get(13).addMember(class5Student.get(8));
		projectData.get(4).getTeams2().get(13).addMember(class5Student.get(11));
		projectData.get(4).getTeams2().get(14).addMember(class5Student.get(7));
		projectData.get(4).getTeams2().get(14).addMember(class5Student.get(6));
		projectData.get(4).getTeams2().get(14).addMember(class5Student.get(15));
		projectData.get(4).getTeams2().get(14).addMember(class5Student.get(13));
		projectData.get(4).getTeams2().get(15).addMember(class5Student.get(4));
		projectData.get(4).getTeams2().get(15).addMember(class5Student.get(14));
		projectData.get(4).getTeams2().get(15).addMember(class5Student.get(1));
		projectData.get(4).getTeams2().get(15).addMember(class5Student.get(0));
		projectData.get(5).getTeams2().get(0).addMember(class6Student.get(12));
		projectData.get(5).getTeams2().get(0).addMember(class6Student.get(5));
		projectData.get(5).getTeams2().get(0).addMember(class6Student.get(2));
		projectData.get(5).getTeams2().get(0).addMember(class6Student.get(13));
		projectData.get(5).getTeams2().get(1).addMember(class6Student.get(8));
		projectData.get(5).getTeams2().get(1).addMember(class6Student.get(7));
		projectData.get(5).getTeams2().get(1).addMember(class6Student.get(4));
		projectData.get(5).getTeams2().get(1).addMember(class6Student.get(6));
		projectData.get(5).getTeams2().get(2).addMember(class6Student.get(1));
		projectData.get(5).getTeams2().get(2).addMember(class6Student.get(11));
		projectData.get(5).getTeams2().get(2).addMember(class6Student.get(3));
		projectData.get(5).getTeams2().get(2).addMember(class6Student.get(9));
		projectData.get(5).getTeams2().get(3).addMember(class6Student.get(10));
		projectData.get(5).getTeams2().get(3).addMember(class6Student.get(15));
		projectData.get(5).getTeams2().get(3).addMember(class6Student.get(14));
		projectData.get(5).getTeams2().get(3).addMember(class6Student.get(0));
		projectData.get(5).getTeams2().get(4).addMember(class6Student.get(6));
		projectData.get(5).getTeams2().get(4).addMember(class6Student.get(5));
		projectData.get(5).getTeams2().get(4).addMember(class6Student.get(10));
		projectData.get(5).getTeams2().get(4).addMember(class6Student.get(7));
		projectData.get(5).getTeams2().get(5).addMember(class6Student.get(2));
		projectData.get(5).getTeams2().get(5).addMember(class6Student.get(11));
		projectData.get(5).getTeams2().get(5).addMember(class6Student.get(1));
		projectData.get(5).getTeams2().get(5).addMember(class6Student.get(0));
		projectData.get(5).getTeams2().get(6).addMember(class6Student.get(12));
		projectData.get(5).getTeams2().get(6).addMember(class6Student.get(15));
		projectData.get(5).getTeams2().get(6).addMember(class6Student.get(4));
		projectData.get(5).getTeams2().get(6).addMember(class6Student.get(3));
		projectData.get(5).getTeams2().get(7).addMember(class6Student.get(13));
		projectData.get(5).getTeams2().get(7).addMember(class6Student.get(9));
		projectData.get(5).getTeams2().get(7).addMember(class6Student.get(14));
		projectData.get(5).getTeams2().get(7).addMember(class6Student.get(8));
		projectData.get(5).getTeams2().get(8).addMember(class6Student.get(12));
		projectData.get(5).getTeams2().get(8).addMember(class6Student.get(8));
		projectData.get(5).getTeams2().get(8).addMember(class6Student.get(2));
		projectData.get(5).getTeams2().get(8).addMember(class6Student.get(9));
		projectData.get(5).getTeams2().get(9).addMember(class6Student.get(3));
		projectData.get(5).getTeams2().get(9).addMember(class6Student.get(15));
		projectData.get(5).getTeams2().get(9).addMember(class6Student.get(7));
		projectData.get(5).getTeams2().get(9).addMember(class6Student.get(11));
		projectData.get(5).getTeams2().get(10).addMember(class6Student.get(4));
		projectData.get(5).getTeams2().get(10).addMember(class6Student.get(0));
		projectData.get(5).getTeams2().get(10).addMember(class6Student.get(14));
		projectData.get(5).getTeams2().get(10).addMember(class6Student.get(1));
		projectData.get(5).getTeams2().get(11).addMember(class6Student.get(5));
		projectData.get(5).getTeams2().get(11).addMember(class6Student.get(10));
		projectData.get(5).getTeams2().get(11).addMember(class6Student.get(6));
		projectData.get(5).getTeams2().get(11).addMember(class6Student.get(13));
		projectData.get(5).getTeams2().get(12).addMember(class6Student.get(2));
		projectData.get(5).getTeams2().get(12).addMember(class6Student.get(1));
		projectData.get(5).getTeams2().get(12).addMember(class6Student.get(9));
		projectData.get(5).getTeams2().get(12).addMember(class6Student.get(14));
		projectData.get(5).getTeams2().get(13).addMember(class6Student.get(8));
		projectData.get(5).getTeams2().get(13).addMember(class6Student.get(15));
		projectData.get(5).getTeams2().get(13).addMember(class6Student.get(11));
		projectData.get(5).getTeams2().get(13).addMember(class6Student.get(3));
		projectData.get(5).getTeams2().get(14).addMember(class6Student.get(10));
		projectData.get(5).getTeams2().get(14).addMember(class6Student.get(4));
		projectData.get(5).getTeams2().get(14).addMember(class6Student.get(7));
		projectData.get(5).getTeams2().get(14).addMember(class6Student.get(0));
		projectData.get(5).getTeams2().get(15).addMember(class6Student.get(6));
		projectData.get(5).getTeams2().get(15).addMember(class6Student.get(12));
		projectData.get(5).getTeams2().get(15).addMember(class6Student.get(5));
		projectData.get(5).getTeams2().get(15).addMember(class6Student.get(13));

		//산출물 추가
		try (FileReader fr = new FileReader(new File("resource\\data\\outputList.txt"))) {
			StringBuilder sb = new StringBuilder();
			int readData;
			while ((readData = fr.read()) != -1) {
				sb.append((char) readData);
			}
			StringTokenizer stk = new StringTokenizer(sb.toString(), "\n");
			for (int i = 0; i < projectData.size(); i++) {
				//				for (int j = 0; j < projectData.get(i).getTeams2().size() - 1; j++) {
				for (int j = 0; j < projectData.get(i).getTeams2().size(); j++) {
					if (stk.hasMoreTokens()) {
						projectData.get(i).getTeams2().get(j).setOutput(new Output(stk.nextToken()));
					}
				}
			} //산출물 입력 for
		} //try
		catch (Exception e) {
			e.printStackTrace();
		}
		//태그 추가
		projectData.get(0).getTeams2().get(0).getOutput().getTagList().add(TagRepository.getOutputTags().get(0));
		projectData.get(0).getTeams2().get(0).getOutput().getTagList().add(TagRepository.getOutputTags().get(2));
	}//생성자

	public List<Project> getProjects() {
		return projectData;
	}
}